name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Vitest
        run: |
          npm ci
          npm run dev:prepare
          npm run prepack
          npm run test:ci

      - name: Prettier
        run: |
          npm run prettier

      - name: nuxi typecheck
        run: |
          npm run typecheck
